#!/bin/bash

COMMIT_EDITMSG_FILE_PATH=$1
DEFAULT_COMMIT_MSG=$(cat $COMMIT_EDITMSG_FILE_PATH)

CURRENT_BRANCH_NAME=$(git rev-parse --abbrev-ref HEAD)
ISSUE_TICKET=$(echo "$CURRENT_BRANCH_NAME" | sed 's/.*\///')

if [ "$COMMIT_SOURCE" != "merge" ]; then
  if [[ "$DEFAULT_COMMIT_MSG" != "[#$ISSUE_TICKET]"* ]]; then
    PREFIX="[#$ISSUE_TICKET] "
  fi
fi

echo "$PREFIX$DEFAULT_COMMIT_MSG" > $COMMIT_EDITMSG_FILE_PATH